### ISSUE TITLE
request is handled after channel closed

### ISSUE THREAD

**Issue by naah69** [reactor/reactor-netty#3518]
## Expected Behavior
request will not be handled after channel closed .

channel won't close initiative until keepalive timeout when enable tcp keepalive 

## Actual Behavior
request is handled after channel closed,the backend service will throw exception that is `Connection was closed `

![image](https://github.com/user-attachments/assets/c7d09e9e-96aa-46ea-97a6-d02895d68c91)

## Steps to Reproduce

It have the problem when the qps of service is high

Broswer -》Nginx -》Gateway(reactor-netty httpclient) -》Service

[wiretap debug log](https://github.com/user-attachments/files/17916484/4.log)

<img width="1433" alt="image" src="https://github.com/user-attachments/assets/1550dafe-23c0-4824-94eb-4e490cf0da2a">

httpclient config:
```yaml
  httpclient:
    strategy: netty
    keepAlive: true
    soKeepAlive: true
    allIdleTime: 3000
    readerIdleTime: 3000
    writerIdleTime: 3000
    connectTimeout: 45000
    readTimeout: 3000
    writeTimeout: 3000
    maxInMemorySize: 200
    wiretap: true
    pool:
      type: ELASTIC
      name: proxy
      maxConnections: 2000
      max-idle-time: 60000
    thread-pool:
      select-count: 8
      worker-count: 64
      prefix: shenyu-netty-httpclient
```

## Possible Solution
sry，I don't know, I need help

## Your Environment

* Reactor version(s) used: 1.0.34
* Other relevant libraries versions: netty 4.1.77
* JVM version (`java -version`): jdk17
* OS and version (eg. `uname -a`): centos 7
